# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6610728d3ec50e018cd9695cc524dfc382356b01937f6184335557cee1a1a8e81e3b5f03f813be91a48ded82930f68982c334163fb5bf1c8313248690abed704

test:
  secret_key_base: b386e1a4fd9618beafb6f523980a185a66840c92210efea913c161d54a98df22766fb1d127d55e6fe501c6ba079c86981e20448035b9d4770fa699c79a011ac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
